# shared configuration for both
# ------------------------------------------------------------------------------

rabbitmq_connection: amqp://user:password@localhost:5672/
rabbitmq_key: test-key

# backend
# ------------------------------------------------------------------------------
url: https://infomark-staging.informatik.uni-tuebingen.de
log_level: debug
port: 0.0.0.0:3000
redis_url: redis://localhost:6379/0

# authentication
auth_jwt_secret: fffff
auth_jwt_access_expiry: 15m
auth_jwt_refresh_expiry: 10h
auth_session_secret: u46IpCV9y5Vlur8YvODJEhgOY8m9JVE4sdfdfsdf
auth_total_requests_per_minute: 600
auth_cookie_lifetime: 24h
auth_cookie_idle_timeout: 60m

# when using https (should be true)
auth_secure_cookie: false

# database
database_connection: postgres://user:pass@localhost:5433/db?sslmode=disable&connect_timeout=1
db_debug: false

# email
email_from: no-reply@info2.informatik.uni-tuebingen.de
sendmail_binary: /usr/sbin/sendmail
email_channel_size: 300


min_password_length: 7
cronjob_intervall_submission_zip: every 120s
use_backend_worker: true

uploads_dir: /var/www/infomark-staging/app/files/uploads
common_dir: /var/www/infomark-staging/app/files/common
generated_files_dir: /var/www/infomark-staging/app/files/generated_files
fixtures_dir: /var/www/infomark-staging/app/files/fixtures

server_read_timeout_sec: 30
server_write_timeout_sec: 30

server_max_header_bytes: 1048576      # default is 1MB = 1048576 bytes
max_request_json_bytes: 2097152       # 2 * 1024 * 1024 = 2097152
max_request_avatar_bytes: 1048576     # 1 * 1024 * 1024 = 1048576
max_request_submission_bytes: 4194304 # 4 * 1024 * 1024 = 4194304

debug_user_enabled: false
debug_user_id: 1
debug_user_is_root: false

# worker
# ------------------------------------------------------------------------------
worker_workdir: /tmp
worker_void: false  # true -> background jobs are always skipped
worker_docker_memory_bytes: 209715200 # 200 * 1024 * 1024 = 209715200